{% set name = "litestar-htmx" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_')}}-{{ version }}.tar.gz
  sha256: e02d1a3a92172c874835fa3e6749d65ae9fc626d0df46719490a16293e2146fb

build:
  number: 1
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - litestar_htmx
  requires:
    - pip
    - pytest
    - anyio
    - litestar
    - jinja2
    - mako
  commands:
    - pip check
    - pytest tests/ -x -v

about:
  home: https://github.com/litestar-org/litestar-htmx
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: HTMX Integration for Litestar
  description: Litestar HTMX provides request and response classes, types, and a plugin for working with HTMX in Litestar applications.
  doc_url: https://litestar-org.github.io/litestar-htmx
  dev_url: https://github.com/litestar-org/litestar-htmx

extra:
  recipe-maintainers:
    - bollwyvl
